namespace PayItForward.Data.Models.Abstraction
{
    using System;

     // Audit Model which represent the audit log generated by the system when any changes has been made in database.
    public interface IAuditInfo
    {
        DateTime CreatedOn { get; set; }

        DateTime? ModifiedOn { get; set; }
    }
}
